### ISSUE TITLE
Issues with binding

### ISSUE THREAD

**Issue by holm** [FredKSchott/fflip-express#1]
In the readme, it is said that the middleware should be used like this:

`app.use(fflipExpress.middleware);`

That however will cause the middleware function to have no `this`, and fail when it tries to access the options stored on `this`. It can be worked around by binding the function, but that is not super elegant.

Perhaps the middleware function should be a factory, that returns the connect function instead?

**Comment by FredKSchott** [comment]
Ah crap, you're right. Good catch.

To work around this you for now you'll have to properly bind it yourself
(using 'fflipExpress.middleware.bind(fflipExpress)' instead).

For the real solution, a factory would definitely work. We could also
properly bind it ourselves, or use an explicit reference to the module
instead of 'this'.

**Comment by holm** [comment]
Thanks. I figured out the bind easily enough, but it can be a silly thing to stumble on for new users.

**Comment by holm** [comment]
Thanks for the quick fix

**Comment by FredKSchott** [comment]
np!

**Comment by FredKSchott** [comment]
just published as v1.0.1
