### ISSUE TITLE
Remove dependence on express

### ISSUE THREAD

**Issue by cryptiklemur** [FredKSchott/fflip-express#8]
Hi there! Love the library. Any chance you could remove any hard dependencies on express, and just support the native nodejs http lib?

**Comment by FredKSchott** [comment]
fflip works with any server! See https://github.com/FredKSchott/fflip

If you're saying you'd like a plugin like fflip-express but for the "http" module, that would be a little tricky since there's no middleware concept, but definitely possible and you could probably use some of this same code! You can see in this repo all that we do in our middleware is append info to the `req` object: https://github.com/FredKSchott/fflip-express/blob/master/lib/fflip-express.js#L39-L54 

Closing since this isn't an issue, but if you make any progress please lmk and I'll add a link to the README!
